# Generated by Django 3.2.3 on 2021-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freq_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_mod',
            name='frequent_words',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
